cro/urls.py
"""informer_batyr URL Configuration

"""
from django.urls import path

from cro.views import TabInvView, InventResultReport, InventStatsReport
from . import views

urlpatterns = [
    path('table_inv/', views.form_table_inv, name='table_inv'),
    path('invent_report/', InventResultReport.as_view(), name='invent_report_url'),
    # path('invent_report_stats/', InventStatsReport.as_view(), name='invent_report_stats_url'),
    path('invent_report/<str:slug>/', TabInvView.as_view(), name='view_tab_invent_url'),
    path('search_shop/', views.search_shop, name='search_shop_url'),
]

informer_batyr/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from informer_batyr import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('batyr.urls')),
                  path("ckeditor/", include('ckeditor_uploader.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mk/urls.py
"""informer_batyr URL Configuration

"""
from django.contrib import admin
from django.urls import path, include

from mk import views
from mk.views import ChecklistView, MkReport, MkReportEtc, mk_nkro_report

urlpatterns = [
    path('check_list_mk/', views.form_check_list_mk, name='check_list_mk_url'),
    path('mk_report/', MkReport.as_view(), name='mk_report_url'),
    # path('mk_etc_report/', MkReportEtc.as_view(), name='mk_etc_report_url'),
    path('mk_nkro_report/', mk_nkro_report, name='mk_nkro_report_url'),
    path('quality_report/<str:slug>/', ChecklistView.as_view(), name='view_checklist_url'),
    path('search_shop/', views.search_shop, name='mk_search_shop_url'),
    path('search_sv/', views.search_date, name='mk_search_sv_url'),

]

cro/models.py
import datetime
import uuid

from django.db import models
from django.urls import reverse

from batyr.models import Legal_entity, Shop


class WorkerStatusCis(models.Model):
    work_status = models.CharField(max_length=48)

    def __str__(self):
        return "%s" % self.work_status

    class Meta:
        verbose_name = "Должность"
        verbose_name_plural = "Должности"


class WorkerCis(models.Model):
    name = models.CharField(max_length=120, verbose_name="ФИО")
    work_status = models.ForeignKey(WorkerStatusCis, on_delete=models.CASCADE, blank=True, default=None)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Специалист КРО"
        verbose_name_plural = "Специалисты КРО"


class TabInv(models.Model):
    slug = models.SlugField(max_length=120, unique=True, blank=True, default=uuid.uuid4)
    shop = models.CharField(max_length=120, verbose_name="Магазин")
    sv_shop = models.CharField(max_length=100, verbose_name="СВ")
    dm_shop = models.CharField(max_length=100, verbose_name="ДМ")
    date_inv = models.CharField(max_length=120, verbose_name="Дата")
    dm_shop_new = models.CharField(max_length=120, blank=True, default=None, verbose_name="ДМ принимающий")
    res_main = models.DecimalField(max_digits=9, decimal_places=2, default=None, verbose_name="Осн.мето.хр")
    res_defect = models.DecimalField(max_digits=9, decimal_places=2, default=None, verbose_name="Зона Брака")
    res_6_line = models.DecimalField(max_digits=9, decimal_places=2, default=None, verbose_name="Бал. Лок.")
    res_4_line = models.DecimalField(max_digits=9, decimal_places=2, default=None, verbose_name="4 Линия")
    res_total = models.DecimalField(max_digits=9, decimal_places=2, default=None, verbose_name="Итого")
    type_inv = models.CharField(max_length=120, default=None, verbose_name="тип инв")
    format_shop = models.IntegerField(blank=True, default=None, verbose_name="Формат")  # достаем формат с Shop
    fact_format = models.IntegerField(default=None, verbose_name="Формат Факт")
    coment = models.CharField(max_length=120, blank=True, null=True, default=None, verbose_name="Коментарии")
    qky_mop = models.IntegerField(default=None, verbose_name="Кол.Моп")
    fact_qky_mop = models.IntegerField(default=None, verbose_name="Факт.Кол.Моп")
    qky_scro = models.IntegerField(default=None, verbose_name="Кол.СКРО")
    diver_qky_mop = models.IntegerField(default=None, verbose_name="Отклонение")
    vscro = models.CharField(max_length=100, verbose_name="ВСКРО")
    t_o = models.DecimalField(max_digits=15, decimal_places=2, default=None, verbose_name="ТО")
    percent_of_to = models.DecimalField(max_digits=9, decimal_places=2, default=None, verbose_name="% от ТО")
    resort_001 = models.DecimalField(max_digits=9, decimal_places=2, default=None, verbose_name="001 счет")
    previous_date = models.CharField(max_length=40, default=None, verbose_name="Дата пред. инвент")  # АВТОМАТИЗИРОВАТЬ
    time_end = models.CharField(max_length=50, blank=True, default=0, verbose_name="Время окончания инвент")

    class Meta:
        verbose_name = "Таблица инв. СКРО"
        verbose_name_plural = "Таблица инв. СКРО"

    def __str__(self):
        return "%s" % self.shop

    def save(self, *args, **kwargs):
        self.time_end = datetime.datetime.today().strftime("%H:%M")
        self.res_total = self.res_4_line + self.res_6_line + self.res_defect + self.res_main + self.resort_001
        if not self.dm_shop_new:
            self.type_inv = "плановая"
        else:
            self.type_inv = "смена"

        self.diver_qky_mop = self.fact_qky_mop - self.qky_mop
        self.percent_of_to = self.res_total * 100 / self.t_o

        """ подтягиваем формат магазина с дислокации """

        def shop_split_shop_num(shop):  # вытаскиваем №маг в int
            lst = self.shop.split()
            shop_num = int(lst[0])
            return shop_num

        def shop_split_legal_entity(shop):  # вытаскиваем Юр.лицо в id
            lst = self.shop.split()
            legal_entity = str(lst[1])
            legal_entity_id = Legal_entity.objects.get(name=legal_entity).id
            return legal_entity_id

        shop_object = Shop.objects.filter(number_id=shop_split_shop_num(self.shop)).filter(
            legal_entity=shop_split_legal_entity(self.shop))
        shop_get = shop_object.get()
        self.format_shop = shop_get.format

        t = datetime.datetime.now()
        self.slug = str(shop_split_legal_entity(self.shop)) + "-" + str(t.hour) + str(t.minute) + str(t.second)

        super(TabInv, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('view_tab_invent_url', kwargs={'slug': self.slug})

cro/forms.py
from django import forms

from batyr.models import Supervisor, Shop
from cro.models import TabInv, WorkerCis


class TableInvForm(forms.ModelForm):
    vscro = forms.ModelChoiceField(queryset=WorkerCis.objects.filter(work_status_id=1), label="ВСКРО")
    sv_shop = forms.ModelChoiceField(queryset=Supervisor.objects.all(), label="Супервайзер")
    shop = forms.ModelChoiceField(queryset=Shop.objects.all(), label="Магазин")

    class Meta:
        model = TabInv

        fields = ["sv_shop", "shop", "date_inv", "dm_shop", "dm_shop_new", "res_main", "res_defect", "res_6_line",
                  "res_4_line", "resort_001", "t_o", "vscro", "qky_scro", "fact_qky_mop", "qky_mop", "previous_date",
                  "fact_format"]
        exclude = ["slug", "format_shop", "res_total", "type_inv", "percent_of_to", "diver_qky_mop", "coment", "time_end"]

cro/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View

from cro.forms import TableInvForm
from cro.models import TabInv
from cro.utils import ObjectDetailMixin, ObjectSearchMixin, get_slug_last


def form_table_inv(request):
    form = TableInvForm(request.POST or None)

    if request.method == "POST" and form.is_valid():  # Если получаем данные с формы Анкеты

        sv_shop = form.cleaned_data["sv_shop"]
        shop = form.cleaned_data["shop"]
        date_inv = form.cleaned_data["date_inv"]
        dm_shop = form.cleaned_data["dm_shop"]
        dm_shop_new = form.cleaned_data["dm_shop_new"]
        res_main = form.cleaned_data["res_main"]
        res_defect = form.cleaned_data["res_defect"]
        res_6_line = form.cleaned_data["res_6_line"]
        res_4_line = form.cleaned_data["res_4_line"]
        resort_001 = form.cleaned_data["resort_001"]
        t_o = form.cleaned_data["t_o"]
        previous_date = form.cleaned_data["previous_date"]
        vscro = form.cleaned_data["vscro"]
        qky_scro = form.cleaned_data["qky_scro"]
        fact_qky_mop = form.cleaned_data["fact_qky_mop"]
        qky_mop = form.cleaned_data["qky_mop"]
        fact_format = form.cleaned_data["fact_format"]

        new_form = form.save()

        return redirect(get_slug_last(TabInv))

    return render(request, 'form_cro/table_invent.html', locals())


class TabInvView(ObjectDetailMixin, View):
    model = TabInv
    template = 'views_report_cro/tab_invent_view.html'


class InventStatsReport(ObjectSearchMixin, View):
    model = TabInv
    template = 'views_report_cro/invent_stat_report.html'


class InventResultReport(ObjectSearchMixin, View):
    model = TabInv
    template = 'views_report_cro/invent_result_report.html'


def search_shop(request):
    if request.GET:
        shop = request.GET.get('shop')
        res_search = TabInv.objects.filter(shop__contains=shop).values()
        context = {
            'elements': list(res_search)
        }
        return JsonResponse(context)
    else:
        pass

cro/templates/form_cro/table_invent.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container-fluid">
        <br>
            <div class="row">
                <div class="col-6">
                    <form action="" method="post" class="form-group text-center">{% csrf_token %}
                        <table class="table table-bordered table-dark">
                            <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Данные</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in form %}
                                <tr>
                                    <th scope="row" class="col-lg-4" style="text-align: left">{{ item.label }}</th>
                                    <td style="text-align: left">{{ item }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Отправить</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-4">
                    <table class="table table-bordered table-dark">
                        <thead>
                        <tr>
                            <th colspan="2">Результаты Инвентаризации</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">Итого:</th>
                            <td id="result"></td>
                        </tr>
                        <tr>
                            <th scope="row">Итого % от ТО:</th>
                            <td id="precent_to"></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% else %}
        <h1>Нет прав</h1>
    {% endif %}
{% endblock %}
{% block jsscript %}
    <script type="text/javascript">
        jQuery('document').ready(function () {
            $('input.datepicker').Zebra_DatePicker();
            jQuery('input').on('keyup', function () {
                var main, defect, line6, line4, resort, to, result, res_precent_to;
                main = parseInt(jQuery('#id_res_main').val());
                defect = parseInt(jQuery('#id_res_defect').val());
                line6 = parseInt(jQuery('#id_res_6_line').val());
                line4 = parseInt(jQuery('#id_res_4_line').val());
                resort = parseInt(jQuery('#id_resort_001').val());
                to = parseInt(jQuery('#id_t_o').val());
                result = main + defect + line6 + line4 + resort;
                res_precent_to = (result * 100 / to).toFixed(2);

                jQuery('#result').html(result);
                jQuery('#precent_to').html(res_precent_to + "%");

            })

        })
    </script>
{% endblock %}